apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-web
spec:
  replicas: 3
  selector:
    matchLabels:
      env: apache-web
  template:
    metadata:
      name: apache-web
      labels:
        env: apache-web
    spec:
      volumes:
        - name: apache-web
          persistentVolumeClaim:
            claimName: frontend-pvc
      containers:
      - name: frontend
        image: ragh19/phpproject:web_v1
        volumeMounts:
          - mountPath: /var/www/html
            name: apache-web
