apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-web
spec:
  replicas: 3
  selector:
    matchLabels:
      env: apache-web
  template:
    metadata:
      name: apache-web
      labels:
        env: apache-web
    spec:
      containers:
        - name: apache-web
          image: httpd:2.4
          volumeMounts:
            - name: apache-web-data
              mountPath: /var/www/html
      volumes:
        - name: apache-web-data
          persistentVolumeClaim:
            claimName: apache-web-data-pvc
