apiVersion: v1
kind: Pod
metadata:
  name: my-php-app
spec:
  containers:
  - name: my-php-app-container
    image: php:8.1-apache
    env:
    - name: DOCUMENT_ROOT
      value: /var/www/html
    ports:
    - containerPort: 80
    volumeMounts:
    - name: my-app-files
      mountPath: /var/www/html
  volumes:
  - name: my-app-files
    configMap:
      name: my-app-files
---
