apiVersion: v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: php:8.1-apache
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: uploads
              mountPath: /var/www/html/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: apache
spec:
  ports:
    - name: "apache"
      targetPort: 80
      port: 80
      nodePort: 30270
      protocol: TCP
  selector:
    app: apache
  type: NodePort
---