apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  documentroot: /var/www/html
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-php-image:8.1
    volumeMounts:
    - name: html-content
      mountPath: /var/www/html
      subPath: documentroot
  volumes:
  - name: html-content
    configMap:
      name: my-config
---      
