apiVersion: v1
kind: Service
metadata:
  name: httpd-service-inosas
  namespace: httpd-namespace-inosas
spec:
  type: NodePort
  selector:
    app: httpd_app_inosas
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-inosas
  namespace: httpd-namespace-inosas
  labels:
    app: httpd_app_inosas
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpd_app_inosas
  template:
    metadata:
      labels:
        app: httpd_app_inosas
    spec:
      containers:
        - name: httpd-container-inosas
          image: httpd:latest
          ports:
            - containerPort: 80
