apiVersion: v1
kind: Service
metadata:
  name: inosas-goo-app
  namespace: inosas-goo-app
  spec:
    containers:
      - name: inosas-goo-app-server
        image: php:8.1.14-apache
        ports:
          - protocol: TCP
            port: 80
---
