apiVersion: v1
kind: Service
metadata:
  name: goo-mysql
  labels:
    app: goo
spec:
  ports:
    - port: 3306
  selector:
    app: goo
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: goo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goo-mysql
  labels:
    app: goo
spec:
  selector:
    matchLabels:
      app: goo
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: goo
        tier: mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
